Repository gioudi/analyst-sergio-penagos, pull requests merged in 2022-12, with the labels that each got.

#25 Feat/way work
  .eslintrc.js
  src/App.vue
  src/assets/Arrow.png
  src/assets/GrupoTravel.png
  src/components/Background.vue
  src/components/Header.vue
  src/locales/en.json
  src/locales/es.json
  src/steps/ProjectStep.vue
  src/steps/SkillStep.vue
  src/styles/main/_bg_dark.scss
  src/styles/main/_bg_light.scss
Labels: feat

#27 fix-text
  src/components/Background.vue
  src/components/Header.vue
  src/locales/en.json
  src/locales/es.json
  src/steps/HomeStep.vue
  src/steps/ProjectStep.vue
  src/styles/custom.scss
  src/styles/main/_bg_dark.scss
  src/styles/main/_bg_light.scss
Labels: bug, feat, fix

#28 Fix animation
  package-lock.json
  package.json
  src/App.vue
  src/components/Background.vue
  src/components/FooterCustom.vue
  src/components/Header.vue
  src/main.ts
  src/steps/AboutStep.vue
  src/steps/HomeStep.vue
  src/steps/ProjectStep.vue
  src/steps/SkillStep.vue
  src/styles/main/_bg_dark.scss
  src/styles/main/_bg_light.scss
Labels: feat, fix

#30 feat-deploy
  .gitignore
  vue.config.js
Labels: feat, fix

#31 Update README.md
  README.md
Labels: documentation

#32 Fix scroll mobile
  .gitignore
  dist/css/app.8ae41100.css
  dist/css/app.b5533de1.css
  dist/index.html
  dist/js/app.17738f27.js
  dist/js/app.17738f27.js.map
  dist/js/app.e853624a.js
  dist/js/app.e853624a.js.map
  src/components/Header.vue
  src/locales/en.json
  src/locales/es.json
  src/steps/AboutStep.vue
  src/steps/HomeStep.vue
  src/steps/ProjectStep.vue
  src/steps/SkillStep.vue
  src/styles/main/_bg_dark.scss
  src/styles/main/_bg_light.scss
Labels: feat, fix

#33 fix: Delete dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: bug, documentation, fix

#34 fix-projects
  src/App.vue
  src/assets/LandingGoogle.png
  src/locales/en.json
  src/locales/es.json
Labels: bug, wontfix, feat, fix
